version: '3.8'

services:

  client:
    build:
      context: .
      dockerfile: Dockerfile.client
    ports:
      - "0.0.0.0:8080:8080"
      - "50050:50050"
    environment:
      - GRPC_PORT=50050
    networks:
      - optNetwork

  server1:
    build:
      context: .
      dockerfile: Dockerfile.server
    depends_on:
      - client
    ports:
      - "50051:50051"
    environment:
      - ServiceName = server1
      - GRPC_PORT=50051
      - Company=CleanIO
    networks:
        - optNetwork

  server2:
    build:
      context: .
      dockerfile: Dockerfile.server
    depends_on:
      - client
    ports:
      - "50052:50052"
    environment:
      - ServiceName = server2
      - GRPC_PORT=50052
      - Company=toothW
    networks:
      - optNetwork


  server3:
    build:
      context: .
      dockerfile: Dockerfile.server
    depends_on:
      - client
    ports:
      - "50053:50053"
    environment:
      - ServiceName = server3
      - GRPC_PORT=50053
      - Company=Workshoppen
    networks:
      - optNetwork

  server4:
    build:
      context: .
      dockerfile: Dockerfile.customer
    depends_on:
      - client
    ports:
      - "50054:50054"
    environment:
      - ServiceName = server4
      - GRPC_PORT=50054
      - Company=CustA
    networks:
      - optNetwork

  server5:
    build:
      context: .
      dockerfile: Dockerfile.customer
    depends_on:
    - client
    ports:
      - "50055:50055"
    environment:
      - ServiceName = server5
      - GRPC_PORT=50055
      - Company=CustB
    networks:
      - optNetwork


  server6:
    build:
      context: .
      dockerfile: Dockerfile.customer
    depends_on:
      - client
    ports:
      - "50056:50056"
    environment:
      - ServiceName = server6
      - GRPC_PORT=50056
      - Company=Custc
    networks:
      - optNetwork

  optimizer:
    build:
      context: ./optimizer
      dockerfile: Dockerfile
    depends_on:
      - client
    ports:
      - "50060:50060"
    networks:
      - optNetwork


networks:
  optNetwork:
    external: true