version: '3.8'

services:
  server1:
    build:
      context: .
      dockerfile: Dockerfile.server
    ports:
      - "50051:50051"
    environment:
      - GRPC_PORT=50051
      - Company=CleanIO

  server2:
    build:
      context: .
      dockerfile: Dockerfile.server
    ports:
      - "50052:50052"
    environment:
      - GRPC_PORT=50052
      - Company=toothW


  server3:
    build:
      context: .
      dockerfile: Dockerfile.server
    ports:
      - "50053:50053"
    environment:
      - GRPC_PORT=50053
      - Company=Workshoppen

  server4:
    build:
      context: .
      dockerfile: Dockerfile.customer
    ports:
      - "50054:50054"
    environment:
      - GRPC_PORT=50054
      - Company=CustA

  server5:
    build:
      context: .
      dockerfile: Dockerfile.customer
    ports:
      - "50055:50055"
    environment:
      - GRPC_PORT=50055
      - Company=CustB


  server6:
    build:
      context: .
      dockerfile: Dockerfile.customer
    ports:
      - "50056:50056"
    environment:
      - GRPC_PORT=50056
      - Company=Custc

  client:
    build:
      context: .
      dockerfile: Dockerfile.client
    depends_on:
      - server1
      - server2
      - server3
    ports:
      - "0.0.0.0:8080:8080"