# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import DSM_pb2 as DSM__pb2

GRPC_GENERATED_VERSION = '1.71.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in DSM_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class SubmissionServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CheckAvailabilty = channel.unary_unary(
                '/DSM.SubmissionService/CheckAvailabilty',
                request_serializer=DSM__pb2.Process.SerializeToString,
                response_deserializer=DSM__pb2.ProcessResponse.FromString,
                _registered_method=True)
        self.CheckInterest = channel.unary_unary(
                '/DSM.SubmissionService/CheckInterest',
                request_serializer=DSM__pb2.Purchase.SerializeToString,
                response_deserializer=DSM__pb2.PurchaseResponse.FromString,
                _registered_method=True)
        self.EnrollServer = channel.unary_unary(
                '/DSM.SubmissionService/EnrollServer',
                request_serializer=DSM__pb2.Enroll.SerializeToString,
                response_deserializer=DSM__pb2.EnrollResponse.FromString,
                _registered_method=True)
        self.Optimize = channel.unary_unary(
                '/DSM.SubmissionService/Optimize',
                request_serializer=DSM__pb2.OptimizationRequest.SerializeToString,
                response_deserializer=DSM__pb2.OptimizationResponse.FromString,
                _registered_method=True)


class SubmissionServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def CheckAvailabilty(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CheckInterest(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def EnrollServer(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Optimize(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SubmissionServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CheckAvailabilty': grpc.unary_unary_rpc_method_handler(
                    servicer.CheckAvailabilty,
                    request_deserializer=DSM__pb2.Process.FromString,
                    response_serializer=DSM__pb2.ProcessResponse.SerializeToString,
            ),
            'CheckInterest': grpc.unary_unary_rpc_method_handler(
                    servicer.CheckInterest,
                    request_deserializer=DSM__pb2.Purchase.FromString,
                    response_serializer=DSM__pb2.PurchaseResponse.SerializeToString,
            ),
            'EnrollServer': grpc.unary_unary_rpc_method_handler(
                    servicer.EnrollServer,
                    request_deserializer=DSM__pb2.Enroll.FromString,
                    response_serializer=DSM__pb2.EnrollResponse.SerializeToString,
            ),
            'Optimize': grpc.unary_unary_rpc_method_handler(
                    servicer.Optimize,
                    request_deserializer=DSM__pb2.OptimizationRequest.FromString,
                    response_serializer=DSM__pb2.OptimizationResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'DSM.SubmissionService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('DSM.SubmissionService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class SubmissionService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CheckAvailabilty(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/DSM.SubmissionService/CheckAvailabilty',
            DSM__pb2.Process.SerializeToString,
            DSM__pb2.ProcessResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CheckInterest(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/DSM.SubmissionService/CheckInterest',
            DSM__pb2.Purchase.SerializeToString,
            DSM__pb2.PurchaseResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def EnrollServer(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/DSM.SubmissionService/EnrollServer',
            DSM__pb2.Enroll.SerializeToString,
            DSM__pb2.EnrollResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Optimize(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/DSM.SubmissionService/Optimize',
            DSM__pb2.OptimizationRequest.SerializeToString,
            DSM__pb2.OptimizationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
